### PR TITLE
<Fixed Navbar> Modified alignment and font size

### LINKED ISSUE #34: <Fix navbar>Modify the alignment of elements
**Describe the bug**
Fix the alignment of logo and navigation

**Screenshots**

kend

### PR DESCRIPTION
**Pull request by jayk-gupta**
# Suggested changes
1. Modified alignment of navbar
2. Decreased Font size of navigation
3. Decrease size of logo

# Screenshot
kend

Closes #34

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Can the text on the navbar be bold?

**Comment by jayk-gupta** [comment]
> Can the text on the navbar be bold?

Yeah,sure

**Comment by jayk-gupta** [comment]
done

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution!

**Pull request merged**
