### PR TITLE
Update copyright notice line

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
https://www.termsfeed.com/blog/sample-copyright-notices/

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@TechStudent11 What do you think? Does this look better then how it is:

Updated: <copyright-icon> 2022, KendallDoesCoding, All rights reserved.
Original: <copyright-icon>All Rights Reserved by KendallDoesCoding 2022

I like the updated version.

**Comment by TechStudent11** [comment]
> I like the updated version.

Same here! Just, maybe make the text a bit smaller.

image

**Comment by KendallDoesCoding** [comment]
> > I like the updated version.
> 
> Same here! Just, maybe make the text a bit smaller.
> 
> image

Ok, will do that. For everything, or only for the copyright line?

**Comment by TechStudent11** [comment]
> > > I like the updated version.
> > 
> > 
> > Same here! Just, maybe make the text a bit smaller.
> > image
> 
> Ok, will do that. For everything, or only for the copyright line?

everything

**Comment by KendallDoesCoding** [comment]
> > > > I like the updated version.
> > > 
> > > 
> > > Same here! Just, maybe make the text a bit smaller.
> > > image
> > 
> > 
> > Ok, will do that. For everything, or only for the copyright line?
> 
> everything

Ok, to what size in px to you think will look good?

**Comment by TechStudent11** [comment]
```css
p.copyright,
p.email,
p.email2 {
    font-size: 1rem;
}
```

Maybe?

**Comment by KendallDoesCoding** [comment]
> ```css
> p.copyright,
> p.email,
> p.email2 {
>     font-size: 1rem;
> }
> ```
> 
> Maybe?

Ok, I'll try this in another PR.

**Comment by KendallDoesCoding** [comment]
> > ```css
> > p.copyright,
> > p.email,
> > p.email2 {
> >     font-size: 1rem;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe?
> 
> Ok, I'll try this in another PR.

@TechStudent11 That looks good but maybe a little big, in my opinion? #18 

Deploy Preview: https://deploy-preview-18--kendalldoescoding.netlify.app/

**Comment by TechStudent11** [comment]
no that's fine

**Comment by KendallDoesCoding** [comment]
Ok, I'll merge it for now but I may change the size in the future.

**Comment by KendallDoesCoding** [comment]
I should've merged this first, before merging #17 :(

**Comment by KendallDoesCoding** [comment]
Yes, It looks perfect now with the hyperlinks being highlighted, thanks

**Comment by KendallDoesCoding** [comment]
> @TechStudent11 What do you think? Does this look better then how it is:
> 
> Updated: 2022, KendallDoesCoding, All rights reserved. Original: All Rights Reserved by KendallDoesCoding 2022
> 
> I like the updated version.

For some reason this didn't merge properly? I'm reverting this PR and seeing if the preview as that or no.

**Comment by KendallDoesCoding** [comment]
This PR messed with the subdomain directory from showing too?

**Comment by KendallDoesCoding** [comment]
> This PR messed with the subdomain directory from showing too?
> […](#)
> Message ID: ***@***.***> >> >

Fixed everything #19 and 276f404

**Pull request merged**
