### PR TITLE
made changes with height and projectCard

### PR DESCRIPTION
**Pull request by Osauyi**
--added border radius for project card
--replaced height with padding

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
already looks way better. Are we ready for merge or are you doing more changes?

**Comment by Osauyi** [comment]
>already looks way better. Are we ready for merge or are you doing more changes?

Not really

**Comment by Osauyi** [comment]
>Not really

you can merge it thanks

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution!

**Pull request merged**
